// js/data.js

// 1. GİRİŞ VİDEOLARI (Parti başlayınca ilk bunlar oynar)
const introVideos = [
    { src: "assets/videos/BEN.mp4"},
    { src: "assets/videos/ENDER.mp4"},
    { src: "assets/videos/Seyma.mp4"},
    { src: "assets/videos/EREN.mp4"},
    { src: "assets/videos/SEMIH.mp4"},
    { src: "assets/videos/EZGI.mp4"},
    { src: "assets/videos/EFE.mp4"},
    { src: "assets/videos/BATUK.mp4"}
];

// 2. ZAMAN TÜNELİ (Sadece seçilmiş özel anlar - Highlights)
const timelineMemories = [
    {
        type: "image",
        src: "assets/images/78.jpeg", 
        date: "02.05.2022",
        note: "Bu fotoğraf telefonumda bulduğum en eski beraber bulunduğumuz fotoğrafmış",
        duration: 10000 
    },
    {
        type: "image",
        src: "assets/images/SurprizZeynep.jpeg",
        date: "02.05.2022",
        note: "LDGFJKGDFJJGKDFGFDLLKDGFJGFD",
        duration: 10000 
    }
];

// 3. GALERİ (Burada HER ŞEY olacak - Zaman tünelindekiler + Ekstralar)
const fullGallery = [
    "assets/images/EZ1.jpeg",
    "assets/images/EZ2.jpeg",
    "assets/images/EZ3.jpeg",
    "assets/images/EZ4.jpeg",
    "assets/images/EZ5.jpeg",
    "assets/images/EZ6.jpeg",
    "assets/images/EZ7.jpeg",
    "assets/images/1.jpeg", 
    "assets/images/3.jpeg", 
    "assets/images/4.jpeg", 
    "assets/images/5.jpeg",
    "assets/images/6.jpeg",
    "assets/images/7.jpeg",
    "assets/images/9.jpeg",
    "assets/images/10.jpeg",
    "assets/images/11.jpeg",
    "assets/images/12.jpeg",
    "assets/images/13.jpeg",
    "assets/images/14.jpeg",
    "assets/images/17.jpeg",
    "assets/images/18.jpeg",
    "assets/images/19.jpeg",
    "assets/images/21.jpeg",
    "assets/images/22.jpeg",
    "assets/images/23.jpeg",
    "assets/images/25.jpeg",
    "assets/images/26.jpeg",
    "assets/images/27.jpeg",
    "assets/images/28.jpeg",
    "assets/images/29.jpeg",
    "assets/images/30.jpeg",
    "assets/images/31.jpeg",
    "assets/images/32.jpeg",
    "assets/images/33.jpeg",
    "assets/images/34.jpeg",
    "assets/images/36.jpeg",
    "assets/images/37.jpeg",
    "assets/images/38.jpeg",
    "assets/images/39.jpeg",
    "assets/images/41.jpeg",
    "assets/images/42.jpeg",
    "assets/images/43.jpeg",
    "assets/images/44.jpeg",
    "assets/images/45.jpeg",
    "assets/images/46.jpeg",
    "assets/images/47.jpeg",
    "assets/images/48.jpeg",
    "assets/images/49.jpeg",
    "assets/images/50.jpeg",
    "assets/images/51.jpeg",
    "assets/images/52.jpeg",
    "assets/images/53.jpeg",
    "assets/images/54.jpeg",
    "assets/images/55.jpeg",
    "assets/images/56.jpeg",
    "assets/images/57.jpeg",
    "assets/images/58.jpeg",
    "assets/images/59.jpeg",
    "assets/images/61.jpeg",
    "assets/images/62.jpeg",
    "assets/images/64.jpeg",
    "assets/images/65.jpeg",
    "assets/images/66.jpeg",
    "assets/images/68.jpeg",
    "assets/images/69.jpeg",
    "assets/images/71.jpeg",
    "assets/images/72.jpeg",
    "assets/images/73.jpeg",
    "assets/images/74.jpeg",
    "assets/images/75.jpeg",
    "assets/images/76.jpeg",
    "assets/images/77.jpeg",
    "assets/images/78.jpeg",
    "assets/images/79.jpeg",
    "assets/images/81.jpeg",
    "assets/images/82.jpeg",
    "assets/images/83.jpeg",
    "assets/images/84.jpeg",
    "assets/images/85.jpeg",
    "assets/images/86.jpeg",
    "assets/images/87.jpeg",
    "assets/images/88.jpeg",
    "assets/images/89.jpeg",
    "assets/images/90.jpeg",
    "assets/images/91.jpeg",
    "assets/images/92.jpeg",
    "assets/images/93.jpeg",
    "assets/images/94.jpeg",
    "assets/images/95.jpeg",
    "assets/images/96.jpeg",
    "assets/images/97.jpeg",
    "assets/images/98.jpeg",
    "assets/images/99.jpeg",
    "assets/images/100.jpeg",
    "assets/images/101.jpeg",
    "assets/images/102.jpeg",
    "assets/images/103.jpeg",
    "assets/images/104.jpeg",
    "assets/images/105.jpeg",
    "assets/images/107.jpeg",
    "assets/images/106.jpeg",
    "assets/images/108.jpeg",
    "assets/images/109.jpeg",
    "assets/images/110.jpeg",
    "assets/images/111.jpeg",
    "assets/images/112.jpeg",
    "assets/images/113.jpeg",
    "assets/images/surprise.jpeg",
    "assets/images/SurprizZeynep.jpeg",
    "assets/videos/1.mp4",
    "assets/videos/2.mp4",
    "assets/videos/3.mp4",
    "assets/videos/4.mp4",
    "assets/videos/5.mp4",
    "assets/videos/6.mp4",
    "assets/videos/7.mp4",
    "assets/videos/8.mp4",
    "assets/videos/9.mp4",
    "assets/videos/11.mp4",
    "assets/videos/12.mp4",
    "assets/videos/13.mp4",
    "assets/videos/14.mp4",
    "assets/videos/15.mp4",
    "assets/videos/16.mp4",
    "assets/videos/17.mp4",
    "assets/videos/18.mp4",
    "assets/videos/19.mp4",
    "assets/videos/20.mp4",
    "assets/videos/21.mp4",
    "assets/videos/22.mp4",
    "assets/videos/23.mp4",
    "assets/videos/Seyma.mp4",
    "assets/videos/EREN.mp4",
    "assets/videos/EFE.mp4",
    "assets/videos/EZGI.mp4",
    "assets/videos/SEMIH.mp4",
    "assets/videos/BATUK.mp4",
    "assets/videos/ENDER.mp4",
    "assets/videos/BEN.mp4"
];

// 4. SÜRPRİZ MESAJI
const surpriseContent = {
    message: "İyi ki varsın iyi ki doğmuşsun. Nice mutlu beraber senelere. Bu site internet yok olana kadar açık kalacak. Yani dijital ayak izin hep olacak. Şimdi 'fotoğraflar ve videolar' sekmesine gidip fotoları veya videoları inceleyebilirsin. Her yılın bir önceki yılından daha mutlu olması dileğiyle...",
    mediaSrc: "assets/images/surprise.jpeg",
    mediaType: "image"
};

// 5. ARKA PLAN MÜZİĞİ
const playlist = [
    { title: "İyi ki Doğdun Zeynep", src: "assets/audio/iyikidogdun_zeynep.mp3" },
    { title: "Başrol Sensin", src: "assets/audio/Basrol-sensin.mp3" },
    { title: "RUYA", src: "assets/audio/RUYA.mp3" },
    { title: "Kamera", src: "assets/audio/Kamera.mp3" },
    { title: "Naber", src: "assets/audio/Naber.mp3" },
    { title: "Şımarık", src: "assets/audio/Simarik.mp3" },
    { title: "Eşarbını Yan Bağlama", src: "assets/audio/esarbini_yan_baglama.mp3" },
    { title: "Tellocan", src: "assets/audio/tellocan.mp3" },
    { title: "Sailor Song", src: "assets/audio/sailorsong.mp3" },
    { title: "Atlantis", src: "assets/audio/atlantis.mp3" },
    { title: "This Side Of Paradise", src: "assets/audio/thissideofparadise.mp3" },
    { title: "BYE BYE", src: "assets/audio/byebye.mp3" }
];